name: python-type-check

on:
  push:
    branches: [ main test-changed-file ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
              python-version: '3.9'
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          echo ${{ steps.files.outputs.all }}
          echo "~~~~~~~~-"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monkeytype
        run: |
          echo ${{ steps.files.outputs.all }}
          echo "~~~~~~~~-"
          for file in ${{ steps.files.outputs.all }}
          do
            echo ${file}
            cat "${GITHUB_WORKSPACE}/${file}"
            check_extension=${file: -3}
            echo "--------"
            if [ $check_extension = ".py" ]
            then
              monkeytype run ${file}
              monkeytype apply ${file} | tr / . | sed 's/\.py.*//'
              curl --location --request POST 'http://139.59.14.101/send' \
              -H 'Cookie: csrftoken=tkS73MCfhOUEMu86E5dY7iijuWumlG39gLhlonKWpPwZDOF93OGd9uw8emsDkEKI' \
              -H 'X-PREVIOUS-COMMIT: ${{ github.event.before }}' \
              -H 'X-CURRENT-COMMIT: ${{ github.sha }}' \
              -H 'X-FILE-PATH: ${file}' \
              -F 'filenames="${GITHUB_WORKSPACE}/${file}"' \
              -F 'filenames="${GITHUB_WORKSPACE}/${file}"' 
            fi
          done
          
          cat src/script.py
          curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.TEST_SECRET }}" https://api.github.com/repos/xperiments-dev/kodikas/branches/test2

  