name: Kodikas-Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
              python-version: '3.9'
      - id: files
        uses: jitterbit/get-changed-files@v1
      
      - name: Output changed files
        run: |
          echo ${{ steps.files.outputs.all }}
      
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Monkey
        run: |
          # Define a list of files for which we dont have to `run`
          list_of_files=()
          for file in ${{ steps.files.outputs.all }}
          do
            echo ${file}
            check_extension=${file: -3}
            if [ $check_extension = ".py" ]
            then
              monkeytype run ${file}
              file_name=$(echo "${file}" | tr / . | sed 's/\.py.*//')
              monkeytype stub "${file_name}" > traces.txt
              if [ -s traces.txt ]
              then
                # Delete traces file on every iteration
                rm traces.txt
                # Before types are added send original code
                curl --header "Content-Type: multipart/form-data" \
                -H 'x-previous-commit: ${{ github.event.before }}' \
                -H 'x-current-commit: ${{github.event.pull_request.head.sha}}' \
                -H 'x-file-path: '"$file" \
                -F "filenames=@$file" -X POST https://kodikas.xperiments.dev/file-upload/
                monkeytype apply "${file_name}"
                # After types have been added send changed code after renaming file

                echo "^^^^^^^^^^^"
                

                curl --header "Content-Type: multipart/form-data" \
                -H 'x-previous-commit: ${{ github.event.before }}' \
                -H 'x-current-commit: ${{github.event.pull_request.head.sha}}' \
                -H 'x-file-path: '"$file" \
                -F "filenames=@$file" -X POST https://kodikas.xperiments.dev/file-upload/
              
              fi
            fi
          done