name: python-type-check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get SHA 
        run: |
          OUTPUT=$(git rev-parse @~)
          echo "${OUTPUT}"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          base_sha: "f3086e4f71d4b53d442522678f0d9ea86a65fbb2"
       
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      # - name: Use a different commit SHA
      #   id: changed-files-custom-sha
      #   uses: tj-actions/changed-files@v23
      #   with:
      #     sha: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
              python-version: '3.9'
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          echo ${{ steps.files.outputs.all }}
          echo "~~~~~~~~-fire-------"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monkeytype
        run: |
          echo ${{ steps.files.outputs.all }}
          echo "~~~~~~~~-"

          for file in ${{ steps.files.outputs.all }}
          do
            echo ${file}
            check_extension=${file: -3}
            echo "--------"
            if [ $check_extension = ".py" ]
            then
              monkeytype run ${file}
              monkeytype apply ${file} | tr / . | sed 's/\.py.*//'
            fi
          done
          
          cat src/script.py
          curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.TEST_SECRET }}" https://api.github.com/repos/xperiments-dev/kodikas/branches/test2

  