name: python-type-check

on:
  push:
    branches: [ main test-changed-file ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
              python-version: '3.9'
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          echo ${{ steps.files.outputs.all }}
          echo "~~~~~~~~~"
      
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run monkeytype
        run: |
          for file in ${{ steps.files.outputs.all }}
          do
            echo ${file}

            check_extension=${file: -3}
            if [ $check_extension = ".py" ]
            then

              # Before types are added send original code
              curl --header "Content-Type: multipart/form-data" \
              -H 'X-PREVIOUS-COMMIT: ${{ github.event.before }}' \
              -H 'X-CURRENT-COMMIT: ${{github.event.pull_request.head.sha}}' \
              -H 'X-FILE-PATH: '"$file" \
              -F "filenames=@$file" -X POST http://139.59.14.101/file-upload

              monkeytype run ${file}
              file_name="${file}" | tr / . | sed 's/\.py.*//'
              monkeytype stub "$file_name"

              if [ -s traces.txt ]
              then
                file_name="${file}" | tr / . | sed 's/\.py.*//'
                monkeytype apply "$file_name"


                # After types have been added send changed code
                curl --header "Content-Type: multipart/form-data" \
                -H 'X-PREVIOUS-COMMIT: ${{ github.event.before }}' \
                -H 'X-CURRENT-COMMIT: ${{github.event.pull_request.head.sha}}' \
                -H 'X-FILE-PATH: '"$file" \
                -F "filenames=@$file" -X POST http://139.59.14.101/file-upload
              fi
            fi
          done
          
  