name: python-type-check

on:
  push:
    branches: [ main test-changed-file ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
              python-version: '3.9'
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          echo ${{ steps.files.outputs.all }}
          echo "~~~~~~~~-"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monkeytype
        run: |
          echo ${{ steps.files.outputs.all }}
          echo "~~~~~~~~-"

          for file in ${{ steps.files.outputs.all }}
          do
            echo ${file}
            check_extension=${file: -3}
            echo "--------"
            if [ $check_extension = ".py" ]
            then
              ORIGINAL=$(cat ${file})
              monkeytype run ${file}
              monkeytype apply ${file} | tr / . | sed 's/\.py.*//'
              CHANGED=$(cat ${file})
              curl --location --request POST '127.0.0.1:8000/send' \
              --header 'Content-Type: application/json' \
              --header 'Cookie: csrftoken=tkS73MCfhOUEMu86E5dY7iijuWumlG39gLhlonKWpPwZDOF93OGd9uw8emsDkEKI' \
              --data-raw '{
                  "previous_commit_sha":"${github.event.before}",
                  "current_commit_sha": "${github.sha}",
                  "changed_code": "${CHANGED}",
                  "original_code": "${ORIGINAL}",
                  "file_path": "${file}"
              }'
            fi
          done
          
          cat src/script.py
          curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.TEST_SECRET }}" https://api.github.com/repos/xperiments-dev/kodikas/branches/test2

  