name: CI-python-type-check

on:
  push:
    branches: [ main fix/final-gh-action ]
  pull_request:
    branches: [ main fix/final-gh-action ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
              python-version: '3.9'
      - id: files
        uses: jitterbit/get-changed-files@v1

      - name: Run monkeytype
        run: |
          pip3 install MonkeyType
          pip3 install requests
          echo ${{ steps.files.outputs.all }}

          for file in ${{ steps.files.outputs.all }}
          do
            echo ${file}
            echo "--------"
            if [ ! $file = ".github/workflows/blank.yml" ]
            then
              monkeytype run ${file}
              monkeytype apply ${file} | tr / . | sed 's/\.py.*//'
            fi
          done
          
          cat src/script.py
          curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.TEST_SECRET }}" https://api.github.com/repos/xperiments-dev/kodikas/branches/test2

  